- name: slack-send
  # You may pin to the exact commit or the version.
  # uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117
  uses: slackapi/slack-github-action@v1.24.0
  with:
    # Slack channel ID where message will be posted. Needed if using bot token
    channel-id: # optional
    # Message to post into Slack. Needed if using bot token
    slack-message: # optional
    # JSON payload to send to Slack if webhook route. If not supplied, json from GitHub event will be sent instead
    payload: # optional
    # path to JSON payload to send to Slack if webhook route. If not supplied, json from GitHub event will be sent instead. If payload is provided, it will take preference over this field
    payload-file-path: # optional
    # The timestamp of a previous message posted. It will update the existing message instead of posting a new message
    update-ts: # optional
- name: Send GitHub Action trigger data to Slack workflow
  id: slack
  uses: slackapi/slack-github-action@v1.24.0
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
