name: 'Send github'
on:
  push:
    paths:
      - 'components/**'

jobs:
  # Gather all changed files into a matrix
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          json: true
          quotepath: false
          escape_json: false
          files: |
            **.js
            **.jsx
            **.ts
            **.tsx
            
  # Report each changed file in the matrix using a separate slack webhook call
  report-changes:
    name: Report changes to slack
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: 
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 2
      fail-fast: true
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "event_type": "PUSH",
              "user_id": "${{ github.event.pusher.name }}",
              "user_email": "${{ github.event.pusher.email }}",
              "file_name": "${{ matrix.files }}",
              "passcode":"${{ secrets.SLACK_GITHUB_WEBHOOK_PASSCODE }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GITHUB_WEBHOOK }}

  # Debug the data being sent
  debug:
    name: Debug logging
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: 
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
    steps:
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          {
            "user_id": "${{ github.event.pusher.name }}",
            "user_email": "${{ github.event.pusher.email }}",
            "file_name": "${{ matrix.files }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
