name: 'Send github'
on:
  push:
    paths:
      - 'components/**'

jobs:
  # my-job:
  #   name: My Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send GitHub Action trigger data to Slack workflow
  #       id: slack
  #       uses: slackapi/slack-github-action@v1.24.0
  #       with:
  #         # This data can be any valid JSON from a previous step in the GitHub Action
  #         payload: |
  #           {
  #             "user_id": "${{ github.event.pusher.name }}",
  #             "user_email": "${{ github.event.pusher.email }}",
  #             "misc_data": "something"
  #           }
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  output-all:
    name: Output commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Get all changed files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        with:
          files: |
            **.ts*
            **.js*
          since_last_remote_commit: true 
        
      # - name: send changes
      #   id: send-changes
      #   # uses: slackapi/slack-github-action@v1.24.0
      #   run: |
      #     for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
      #       uses: slackapi/slack-github-action@v1.24.0
      #       with:
      #         payload: |
      #           {
      #             "user_id": "${{ github.event.pusher.name }}",
      #             "user_email": "${{ github.event.pusher.email }}",
      #             "misc_data": "$file"
      #           }
      #       env:
      #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     done
      #   # env:
      #   #   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "user_id": "${{ github.event.pusher.name }}",
              "user_email": "${{ github.event.pusher.email }}",
              "misc_data": "${{ steps.changed-files.outputs.all_changed_files }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
  update-sync:
    name: Update sync state
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "file_name": "Components",
              "passcode":"${{ secrets.SLACK_GITHUB_WEBHOOK_PASSCODE }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GITHUB_WEBHOOK }}
