name: 'Send github'
on:
  push:
    paths:
      - 'components/**'

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "user_id": ${{ github.pusher.name }},
              "user_email": ${{ github.event.pusher.email }},
              "misc_data": 'something'
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
