name: 'Send github'
on:
  push:
    paths:
      - 'components/**'

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          json: true
          quotepath: false
          escape_json: false
          files: |
            **.js
            **.jsx
            **.ts
            **.tsx

  report-changes:
    name: Report changes to slack
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: 
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 2
      fail-fast: true
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "file_name": "${{ matrix.value }}",
              "passcode":"${{ secrets.SLACK_GITHUB_WEBHOOK_PASSCODE }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GITHUB_WEBHOOK }}
          
  # output-all:
  #   name: Output commit
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

  #     # Get all changed files
  #     - name: Get changed files
  #       id: get-changed-files
  #       uses: tj-actions/changed-files@v40
  #       # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
  #       with:
  #         files: |
  #           **.js
  #           **.jsx
  #           **.ts
  #           **.tsx
  #         # since_last_remote_commit: true


          
  #     # # Send updates
  #     # - name: Send each changed file
  #     #   id: send-changes
  #     #   run: |
  #     #     for file in ${{ steps.get-changed-files.outputs.all_changed_files }}; do
  #     #       echo "sending $file"
  #     #       uses: slackapi/slack-github-action@v1.24.0
  #     #       with:
  #     #         payload: |
  #     #           {
  #     #             "user_id": "${{ github.event.pusher.name }}",
  #     #             "user_email": "${{ github.event.pusher.email }}",
  #     #             "misc_data": "$file"
  #     #           }
  #     #       env:
  #     #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #     #     done

  #     - name: Send GitHub Action trigger data to Slack workflow
  #       id: slack
  #       uses: slackapi/slack-github-action@v1.24.0
  #       with:
  #         # This data can be any valid JSON from a previous step in the GitHub Action
  #         payload: |
  #           {
  #             "user_id": "${{ github.event.pusher.name }}",
  #             "user_email": "${{ github.event.pusher.email }}",
  #             "file_name": "${{ steps.get-changed-files.outputs.all_changed_files }}"
  #           }
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
  # update-sync:
  #   name: Update sync state
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send GitHub Action trigger data to Slack workflow
  #       id: slack
  #       uses: slackapi/slack-github-action@v1.24.0
  #       with:
  #         payload: |
  #           {
  #             "file_name": "components/Components.ts",
  #             "passcode":"${{ secrets.SLACK_GITHUB_WEBHOOK_PASSCODE }}"
  #           }
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GITHUB_WEBHOOK }}
          
